services:
  - type: web
    name: vyzns
    runtime: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/vyzns-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
